"""
Custom Exception Handler for Secure Error Responses
===================================================
Provides consistent, secure error responses without leaking sensitive information.
"""

from rest_framework.views import exception_handler
from rest_framework.response import Response
from rest_framework import status
import logging

logger = logging.getLogger('django.security')


def custom_exception_handler(exc, context):
    """
    Custom exception handler that:
    1. Logs all errors securely
    2. Returns generic messages to users (no sensitive data leakage)
    3. Logs detailed errors for admin review
    """
    
    # Get default exception handler response
    response = exception_handler(exc, context)
    
    request = context.get('request')
    user = request.user if request else None
    
    # Log the exception
    error_data = {
        'error_type': exc.__class__.__name__,
        'path': request.path if request else 'unknown',
        'method': request.method if request else 'unknown',
        'user': user.email if user and user.is_authenticated else 'anonymous',
        'ip': request.META.get('REMOTE_ADDR', 'unknown') if request else 'unknown',
    }
    
    logger.error(f'API Exception: {error_data}', exc_info=True)
    
    # If response wasn't generated by exception handler, create one
    if response is None:
        response = Response(
            {'error': 'An error occurred processing your request'},
            status=status.HTTP_500_INTERNAL_SERVER_ERROR
        )
    
    # Customize response for specific error types
    if response.status_code == status.HTTP_403_FORBIDDEN:
        response.data = {'error': 'You do not have permission to perform this action'}
    
    elif response.status_code == status.HTTP_401_UNAUTHORIZED:
        response.data = {'error': 'Authentication credentials were not provided'}
    
    elif response.status_code == status.HTTP_400_BAD_REQUEST:
        # Pass validation errors through directly so frontend can display them
        pass
    
    elif response.status_code == status.HTTP_404_NOT_FOUND:
        response.data = {'error': 'Resource not found'}
    
    elif response.status_code == status.HTTP_429_TOO_MANY_REQUESTS:
        response.data = {'error': 'Too many requests. Please try again later'}
    
    elif response.status_code == status.HTTP_500_INTERNAL_SERVER_ERROR:
        response.data = {'error': 'An error occurred processing your request'}
    
    return response
