# Generated by Django 4.2.16 on 2026-03-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_cancel_reason_alter_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='pub_type',
            field=models.CharField(choices=[('article', 'Article'), ('journal', 'Journal'), ('document', 'Document'), ('image', 'Image')], default='article', max_length=20),
        ),
    ]
