# Generated by Django 4.2.16 on 2026-03-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_publication_pub_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
